### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AlexanderHentzsch** [AlexanderHentzsch/jw-notes#1]
- [x] Speichern
- [x] Export JSON
- [x] UI Überarbeiten (Blackmode)
- [x] Fullscreenmode
- [x] Akkusaver durch Video im Hintergrund deaktivieren
- [ ] Akku nach 1 Min schonen: Alles ausblenden > Tippen: alles Anzeigen
- [ ] Tooltip über geschriebenen Text für Optionen
- [ ] Tooltip-Optionen: Bibelstelle aufschlagen, Text markieren
- [ ] Bibeltexte kommentierbar
- [ ] Programm (Kongress) hinterlegen
- [ ] Navigation durch Programm
- [ ] Text durch Textarea ersetzen
- [x] Headline im Content-Bereich
- [ ] Markdown unterstützung
- [ ] Markdown export
