### ISSUE TITLE
TODO Redesign

### ISSUE THREAD

**Issue by AlexanderHentzsch** [AlexanderHentzsch/jw-notes#2]
- [x] Router anlegen
- [x] Optionen als globale json Datei
- [x] Notizen als globale json Datei

### Startseite
(Optionen beachten)
- [x] Vollbildmodus nach Klick
- [x] Energie-Safer durch Video deaktivieren

### Header
- [x] Zurück-Button
- [x] Optionen-Button
- [x] Titel

### Tabs
- [x] Notizen
- [x] Programme

### Content für Notizen
- [x] Bereits angelegte Notizen
- [x] Neue Notiz anlegen >>> Editor >>> Titel: Aktuelles Datum

### Content für Programme
- [ ] Programme auflisten
- [ ] Neues Programm anlegen

### Neues Programm anlegen
- [ ] Import von Text: JW.ORG
- [ ] Texterkennung >>> JSON

### Content für Programm-Notizen
- [ ] Bereits angelegte Notizen
- [ ] Neue Notiz anlegen

### Notizen
- [x] Titel bearbeiten (Nur Notizen)
- [x] Datum automatisch speichern (letzte Änderung)
- [ ] Input-Tag
- [ ] Bibelstellen Erkennung
    - [ ] Format: @[Inhalt]
    - [ ] Kommentare zu Bibelstellen
- [ ] Optionen für Input-Tag
    - [ ] Quelle öffnen
    - [ ] Automatisch Inhalt zu Quelle machen >>> @[Inhalt]
    - [ ] Markieren: 4 Farben
    - [x] löschen
    - [x] ändern
    - [x] speichern
- [x] Datum als Titel erkennen und bei Edit löschen
- [x] Leere Titel durch aktuelles Datum ersetzen

### Optionen
- [ ] Bildschirm nicht ausschalten
- [ ] Vollbildmodus
- [x] Download BackUp
- [x] Import BackUp
- [ ] Lizenzen
