### ISSUE TITLE
TODO v1.1

### ISSUE THREAD

**Issue by AlexanderHentzsch** [AlexanderHentzsch/jw-notes#3]
- [ ] Bibeltexte ausschreiben lassen
- [ ] Bibeltext anklicken > Edit, Über der Toolbox Link zum öffnen, Bibelstelle ausgeschrieben, Schriftgröße anpassbar
- [ ] Export
- [ ] Volltextbearbeitung in Textarea
- [ ] Button im Editor: Full-Black > darauf klicken > reaktivieren
- [ ] GitHub Verknüpfung in den Lizenzen
- [ ] Edits nicht über Router um mit der Zurücktaste wieder zur Übersicht zu gelangen, oder History überschreiben
- [ ] Bug: Datum im localStorage wird nicht richtig interpretiert
- [ ] $route: /new auf eigener Seite interprettieren lassen um Links verwenden zu können für "Neue Notizen anlegen"
- [ ] Programme: Die einzelnen Notizen werden in Programmen (nur) gruppiert. Dadurch kann man vor $route /new/TitelDerNeuenNotiz/ prüfen, ob diese Notiz bereits vorhanden ist und ob sie einem Programm angehörig ist
- [ ] Programme anlegen über md String, import, etc.
- [x] Optionen-Schriftgröße: Text über Slider, rechtsbündig, passt sich der Einstellung an, volle Breite
- [x] Black-Titel für Chrome mobile
- [x] Auflistung der Notizen in umgekehrter Reihenfolge (neuste zu erst)
- [x] Datum der letzten Änderung als UNIX-Time
- [x] Label Titel ... wenn vergeben, letzte Änderung
- [x] Fullscreen-Modus entfernen
- [x] Schriftgröße anpassbar
- [x] Toolleiste: Emojis: Stern, Fragezeichen
- [x] Eingabe passt sich dem Inhalt an
